### PR TITLE
add Artax support

### PR DESCRIPTION
**Pull request by goosewobbler**
https://www.artaxcoin.org/
https://bitcointalk.org/index.php?topic=3267175.80

### CODE REVIEW

**Comment by knowself** [comment]
https://twitter.com/ArtaxCoin/status/998362860639137797

**Comment by marsmensch** [comment]
Thanks for the contribution @goosewobbler. @knowself thanks for the link, first time someone ripped my code w/o even a mention :-/

**Comment by goosewobbler** [comment]
I just scanned the doc for differences to my integration but thought it was a bit...suspect.  Look at the guy's site 🤔😒

**Comment by marsmensch** [comment]
That's why i merged & tested your integration (fixed a typo in the git tag). Thanks again!

**Pull request merged**
